# Just for tests
invoiceProcessorConfig:
  frequency: 5000

paymentProcessorConfig:
  frequency: 3000

# Enabled currencies
# Supported —Åurrencies: BTC, XRP, TRX
enabledCoins:
  coins:
    - BTC
    - XRP
    - TRX

# Example values
btcConfig:
  coin:
    user: "user"
    password: "password"
    host: "127.0.0.1"
    port: "18443"
    confirmations: 1
  explorer:
    frequency: 5000

trxConfig:
  coin:
    # Base58Checksum representation of account
    account: "TW4hF7TVhme1STRC2NToDA41RxCx1H2HbS"
    accountAddress: "41dc6c2bc46639e5371fe99e002858754604cf5847"
    privateKey: "92f451c194301b4a1eae3a818cc181e1a319656dcdf6760cdbe35c54b05bb3ec"
    host: "127.0.0.1"
    port: "18190"
    confirmations: 3
  explorer:
    frequency: 3000

xrpConfig:
  coin:
    account: "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh"
    privateKey: "snoPBrXtMeMyMHUVTgbuqAfg1SUTb"
    passPhrase: "masterpassphrase"
    host: "127.0.0.1"
    port: "51234"
  explorer:
    frequency: 5000